### ISSUE TITLE
Templeton College

### ISSUE THREAD

**Issue by JoeHitchen** [AuspeXeu/oxford-rowing#135]
Between 1986 and 1994 (inclusive) Templeton college raced under their own colours. Data appears to be passed correctly from the backend, but there is no frontend style for the crew icon. For example, see Eights '90 bungline 81.

**Comment by AuspeXeu** [comment]
What does their icon look like?

**Comment by JoeHitchen** [comment]
Wiki for the colleges has their colours as blue/yellow like LMH, but with a seemingly lighter blue. My memory of a trophy blade I saw is that it was solid mid-dark blue.

OxBump go with a white dot on a mid-blue background, similar to how they do Magdalen, which looks decent. Given it's all stylised and no one is likely to know/care, I think you can employ some creative licence and do what you want!
