### ISSUE TITLE
Incorrect result for Univ M2, Torpids 2021 Day 3

### ISSUE THREAD

**Issue by JoeHitchen** [AuspeXeu/oxford-rowing#188]
Univ M2 are shown as sharing bungline 8 with Balliol M2 on the third day of Summer Torpids - They should be on bungline 9.

![Screenshot 2021-06-26 at 15-32-11 Oxford Bumps](https://user-images.githubusercontent.com/29120408/123516479-20e03300-d694-11eb-982a-4e2d271f25db.png)

**Comment by AuspeXeu** [comment]
Should be resolved now :)
